id: P18B0A4F3
initial_creation_type: input
source_metadata:
  title: Jamgön Kongtrul Lodrö Thaye Series
  language: bo
  description: Works by or about the great nineteenth century master Jamgön Kongtrul
    Lodrö Thaye ('jam mgon kong sprul blo gros mtha' yas, 1813–1899), one of the pioneers
    of the Rimé movement
  volume:
    f7f95018ea324f259f24068a61bc60a9:
      title: Advice to Lhawang Tashi
      parent: Advice
    09df00eb3cf24353986350aae77eccff:
      title: Mahāmudrā Preliminaries, Main Part & Conclusion
      parent: Advice
    f062eb76f5be461ea5b82b54a0edda17:
      title: 'Mahāmudrā: the Swift Way to Become a Lord of Realization'
      parent: Advice
    7fcc72670b9a4038b31dd7001c5c1f14:
      title: The Kusāli's Instruction on the Nature of Mind
      parent: Advice
    ce47dc90e1af4a4496a1f2070edce89c:
      title: Prayer for Peace and Stability in Tibet
      parent: Aspiration Prayers
    def3787ff6de4fc7bbec70bff0bbd4d4:
      title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives
        of the Supreme Holders of the Non-Sectarian Teachings
      parent: Aspiration Prayers
    fd7ac4315dd447e8a8b965c3114d912d:
      title: 'A Garland of Vajra Gems: The Life and Liberation of the Guru'
      parent: Biography
    65be74814117436080fcc0a146ad9b83:
      title: Biography of Jamgön Kongtrul Lodrö Thaye
      parent: Biography
    0ebe963775d14134a068d8726a0f371a:
      title: The Life and Liberation of Padmākara, the Second Buddha from A Precious
        Garland of Lapis Lazuli
      parent: Biography
    01c44aff1bf74cf2958366881445f4c6:
      title: 'Calling the Guru From Afar: A Prayer to Pierce the Heart with Devotion'
      parent: Calling the Guru From Afar
    1dd30473d1024891a6b3581e17bcd68c:
      title: Ārya Mañjuśrī Tantra Garbha—commentary
      parent: Commentaries
    69016b3b40f54078a9f0178b5676c6c4:
      title: 'The Cascading Essence of Great Bliss: An Empowerment Ritual for the
        Female Practice of the Queen of Great Bliss, from the Heart Essence of the
        Vast Expanse'
      parent: Empowerment Rites
    975d913928ce47928ff6a2707de4acdc:
      title: 'Jewels of Many Colours: Ordinary Fire Pūjas for the Four Activities
        Based on a Single Substance to Easily Conclude Approach and Accomplishment'
      parent: Fire Offering
    a5f872a5127c420e99a439508abab874:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      parent: Guru Rinpoche Prayers
    362b424f1ea2456ebbb8b78986ea684a:
      title: 'The Fount of Longevity: The Chimé Pakmé Nyingtik Lineage Prayer'
      parent: Lineage Prayers
    cea8c637f6384e2d8b79ac88916b0f85:
      title: A Short Supplication to Tārā
      parent: Prayers
    e96e7191bdac4c6a9b707be66ef06056:
      title: Prayer to Jamyang Khyentse Wangpo, Jamgön Kongtrul and Jamyang Khyentse
        Chökyi Lodrö
      parent: Prayers
    3ec1066110a74e3b8ab014b13049be96:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    95a8304e37d0470a80803c3ac32abb9a:
      title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the
        Liberational Life of the Omniscient Jamyang Khyentse Wangpo'
      parent: Prayers
    b34a1eb231f74c08a95b711bc876fa6a:
      title: 'The Melodious Speech of Samantabhadra: A Prayer to the Glorious Master
        Jamgön Kongtrul Thaye'
      parent: Prayers
    36058634a85e47e5a808c7b74591e146:
      title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro
        Yeshe Tsogyal’s Life and Liberation'
      parent: Prayers
    8314a06382cf4663aa3eea979836edce:
      title: 'The Essence of Benefit and Happiness: A Method for Saving Lives'
      parent: Saving Lives
    f7b287e18bfc43a6ac73983671dc5f20:
      title: Prayer to Kongtrul Yönten Gyatso
      parent: Swift Rebirth Prayers
    7b3e4880fcce4065ad2a4c67a8511a78:
      title: 'Music to Adorn the Illusory Display: A Concise Explanation of the Nature
        of the Feast Offering'
      parent: Tsok
    37e96014c68c461fa86a63174fbf3ba6:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-02-28T23:32:21.222957'
last_modified_at: '2022-02-28T23:32:21.222960'
statistics:
  total_words: 32458
  total_non_words: 3131
quality:
  non_words_ratio: 0.1
